language: python
python:
  - "3.5"
install:
  - sudo apt-get update
  # - sudo apt-get install libzmq3 libzmq3-dev
  - wget https://repo.continuum.io/archive/Anaconda3-5.0.0.1-Linux-x86_64.sh
  - bash ./Anaconda3-5.0.0.1-Linux-x86_64.sh -b -p $HOME/anaconda
  - export PATH="$HOME/anaconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -n digicampipe python=3.5
  - source activate digicampipe

  - conda install protobuf=3.0.0 numpy six scipy astropy ipython_genutils decorator
  - conda install matplotlib llvmlite hdf5 ipython h5py zeromq

  - mkdir ctasoft
  - cd ctasoft

  - wget www.isdc.unige.ch/~lyard/repo/ProtoZFitsReader-0.41.Python3.5.Linux.x86_64.tar.gz
  - pip install ProtoZFitsReader-0.41.Python3.5.Linux.x86_64.tar.gz
  - export LD_LIBRARY_PATH=$CONDA_PREFIX/lib/python3.5/site-packages:$LD_LIBRARY_PATH

  - git clone https://github.com/cta-observatory/pyhessio
  - pip install -e pyhessio

  - git clone https://github.com/calispac/ctapipe
  - pip install -e ctapipe

  - git clone https://github.com/calispac/ctapipe-extra
  - pip install -e ctapipe-extra

  - git clone https://github.com/calispac/digicamviewer
  - pip install -e digicamviewer

  - git clone https://github.com/cocov/CTS
  - pip install -e CTS

install:
  - pip install -e .


script:
  - python pipeline_crab.py
