name: digicampipe
channels:
- astropy
- anaconda
- cta-observatory
- defaults
dependencies:
- aenum
- astropy
- astroquery
- ctapipe-extra=0.2.*
- cython
- docopt
- fitsio
- h5py
- hdf5
- iminuit
- jupyter
- matplotlib
- numba
- numpy
- opencv
- photutils
- pip
- protobuf
- pyqt
- pytest
- PyYAML
- scikit-learn
- scikit-image
- scipy
- sphinx_rtd_theme
- traitlets
- pip:
  - msgpack
  - peakutils==1.0.3
  - pytest-benchmark==3.1.1
  - pytest-runner==3.0
  - recommonmark==0.4.0
  - secretstorage
  - sphinx-automodapi
  - git+https://github.com/iminuit/probfit.git
  - https://github.com/cta-sst-1m/protozfitsreader/archive/v1.4.0.tar.gz
  - git+https://github.com/cta-observatory/pyhessio.git
  - git+https://github.com/cta-observatory/ctapipe.git
  - git+https://github.com/cta-sst-1m/CTS.git
  - git+https://github.com/dstndstn/astrometry.net.git
  - https://github.com/cta-sst-1m/histogram/archive/0.3.2.tar.gz
  - git+https://github.com/uvemas/ViTables.git
