name: digicampipe
channels:
- astropy
- anaconda
- cta-observatory
- defaults
dependencies:
- astropy
- astroquery
- ctapipe-extra=0.2.*
- cython
- docopt
- h5py
- hdf5
- iminuit
- matplotlib
- numba
- numpy
- opencv
- photutils
- pip
- protobuf
- pyhessio
- pyqt
- pytest
- PyYAML
- scikit-learn
- scikit-image
- scipy
- sphinx_rtd_theme
- traitlets
- pip:
  - msgpack
  - peakutils==1.0.3
  - pytest-benchmark==3.1.1
  - pytest-runner==3.0
  - recommonmark==0.4.0
  - secretstorage
  - sphinx-automodapi
  - https://github.com/cta-sst-1m/protozfitsreader/archive/using_cython_generated_wrapper.tar.gz
  - git+https://github.com/cta-observatory/ctapipe.git#egg=ctapipe
  - git+https://github.com/cta-sst-1m/CTS.git#egg=CTS
  - git+https://github.com/dstndstn/astrometry.net.git#egg=astrometry
  - https://github.com/calispac/histogram/archive/0.3.2.tar.gz
  - git+https://github.com/uvemas/ViTables.git#egg=vitables
